-- 상품 데이터
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P001', '라네즈 워터 슬리핑 마스크', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P002', '닥터자르트 시카페어 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P003', '아이오페 비타민C 앰플', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P004', '이니스프리 그린티 씨드 세럼', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P005', '에스트라 아토베리어 365 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P006', '한율 어린쑥 수분 진정 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P007', '메디힐 N.M.F 아쿠아 앰플 마스크', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P008', '라운드랩 1025 독도 토너', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P009', '넘버즈인 3번 결광 톤업 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P010', '클리오 킬커버 파운웨어 쿠션', 'Y');

INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P011', '롬앤 쥬시 래스팅 틴트', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P012', '어퓨 퓨어 블록 내추럴 선크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P013', '닥터지 그린 마일드 업 선', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P014', '토리든 다이브인 저분자 히알루론산 세럼', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P015', '마녀공장 퓨어 클렌징 오일', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P016', '라로슈포제 시카플라스트 밤 B5', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P017', '바이오더마 센시비오 H2O', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P018', '센텔리안24 마데카 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P019', 'VT 시카 마스크팩', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P020', '피지오겔 데일리 모이스쳐 테라피 크림', 'Y');

INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P021', '헤라 UV 프로텍터 톤업', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P022', '에뛰드 순정 2x 베리어 인텐스 크림', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P023', '스킨푸드 캐롯 카로틴 카밍 워터 패드', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P024', '미샤 타임 레볼루션 나이트 리페어 앰플', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P025', 'AHC 내추럴 퍼펙션 더블 쉴드 선스틱', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P026', '브링그린 티트리 시카 수딩 토너', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P027', '메디큐브 제로 모공 패드 2.0', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P028', '바닐라코 클린 잇 제로 클렌징 밤', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P029', '닥터알파 비타민C 브라이트닝 앰플', 'Y');
INSERT INTO TB_PRODUCT (PROD_CD, PROD_NM, USE_YN) VALUES ('P030', '달바 화이트 트러플 퍼스트 스프레이 세럼', 'Y');

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR001', 'P001', 18000, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', 5, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR002', 'P003', 22000, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', 7, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR003', 'P005', 15000, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', 3, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR004', 'P008', 12000, DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', 2, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR005', 'P010', 21000, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', 10, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR006', 'P012', 9000, DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', 6, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR007', 'P015', 13000, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', 4, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR008', 'P018', 17000, DATEADD('DAY', -6, CURRENT_TIMESTAMP), DATEADD('DAY', 1, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR009', 'P021', 25000, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', 8, CURRENT_TIMESTAMP));

INSERT INTO TB_PROMOTION (PROMOTION_CD, PROD_CD, PROMO_PRICE, START_DT, END_DT)
VALUES ('PR010', 'P025', 19000, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', 5, CURRENT_TIMESTAMP));